# Generated by Django 5.0.6 on 2024-06-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_recipe_date_created_recipe_recp_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recp_img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
