# Generated by Django 5.0.6 on 2024-06-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_recipe_recp_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recp_img',
            field=models.ImageField(default='', upload_to='home/images'),
        ),
    ]
