# Generated by Django 5.0.6 on 2024-06-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_recipe_recp_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recp_img',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
