# Generated by Django 5.0.6 on 2024-06-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_recipe_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recp_img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
