# Generated by Django 5.0.6 on 2024-06-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_recipe_recp_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('breakfast', 'breakfast'), ('Curry', 'Curry'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('appetizer', 'appetizer'), ('snacks', 'snacks'), ('dessert', 'dessert'), ('drinks', 'drinks')], max_length=200),
        ),
    ]
